Repository imran1289-ah/SOEN390-Team05-W23, pull requests merged in 2023-03, with the labels that each got.

#96 attempting to add a user session
  src/client/package.json
  src/client/src/App.js
  src/client/src/UserSession.js
  src/client/src/components/EditUserProfile.jsx
  src/client/src/components/Navbar.jsx
  src/client/src/components/SignIn.jsx
  src/client/src/components/SignUp.jsx
  src/client/src/components/UserProfile.jsx
  src/client/src/components/UserTimeline.jsx
  src/client/src/css/navbar.css
  src/client/src/css/signin.css
  src/server/controllers/sessionController.js
  src/server/controllers/usersController.js
  src/server/index.js
  src/server/node_modules/.package-lock.json
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/sessionRoutes.js
Labels: enhancement

#95 Fixed backend tests + Password Encryption
  src/server/controllers/resumeAndCoverLetterController.js
  src/server/controllers/usersController.js
  src/server/node_modules/.package-lock.json
  src/server/package-lock.json
  src/server/tests/jobsApplication.test.js
  src/server/tests/signin.test.js
  src/server/tests/uploadResume_cl.test.js
Labels: enhancement, Testing

#108 Recruiter & Admin Roles
  src/client/src/components/EditJobPosting.jsx
  src/client/src/components/JobPosting.jsx
  src/client/src/components/Navbar.jsx
  src/client/src/components/SignUp.jsx
  src/client/src/components/UserTimeline.jsx
  src/client/src/css/signup.css
  src/server/controllers/usersController.js
  src/server/models/user.js
  src/server/tests/editUserProfile.test.js
  src/server/tests/jobsApplication.test.js
  src/server/tests/jobsListing.test.js
  src/server/tests/postJob.test.js
  src/server/tests/sign_up.test.js
  src/server/tests/signin.test.js
  src/server/tests/uploadResume_cl.test.js
Labels: enhancement

#116 download resume and coverletter for a user
  src/client/src/components/EditUserProfile.jsx
Labels: Front End

#121 Usertimeline backend
  src/client/src/components/UserTimeline.jsx
  src/client/src/components/waitingConnections.jsx
  src/server/controllers/usersController.js
  src/server/routes/userRoutes.js
Labels: Back end

#127 Attempt to FIX bug B5 issue #122
  src/client/src/components/SignIn.jsx
Labels: bug fix

#129 CSS fixes and Attempting to Fix User Search Bug
  src/client/src/App.js
  src/client/src/components/PublicUserProfile.jsx
  src/client/src/components/SearchUser.jsx
  src/client/src/components/UserProfile.jsx
  src/client/src/components/UserTimeline.jsx
  src/client/src/css/UserProfile.css
  src/client/src/css/navbar.css
  src/client/src/css/publicuserprofile.css
  src/client/src/css/userTimeline.css
Labels: Front End, bug fix

#131 View Jobs Applied
  README.md
  src/client/package-lock.json
  src/client/package.json
  src/client/src/App.js
  src/client/src/components/JobApplication.jsx
  src/client/src/components/JobListing.jsx
  src/client/src/components/Navbar.jsx
  src/client/src/components/ViewJobsApplied.jsx
  src/client/src/css/viewJobsApplied.css
  src/server/controllers/usersController.js
  src/server/node_modules/.package-lock.json
Labels: Front End, Back end

#138 Adding translation for certain pages
  src/client/package-lock.json
  src/client/package.json
  src/client/src/App.js
  src/client/src/components/Chat.jsx
  src/client/src/components/ChatInput.jsx
  src/client/src/components/Contacts.jsx
  src/client/src/components/EditUserProfile.jsx
  src/client/src/components/LoginFooter.jsx
  src/client/src/components/Navbar.jsx
  src/client/src/components/PublicUserProfile.jsx
  src/client/src/components/SearchUser.jsx
  src/client/src/components/SignIn.jsx
  src/client/src/components/SignUp.jsx
  src/client/src/components/SignupFooter.jsx
  src/client/src/components/UserProfile.jsx
  src/client/src/components/UserTimeline.jsx
  src/client/src/components/ViewJobsApplied.jsx
  src/client/src/components/waitingConnections.jsx
  src/client/src/i18next.js
  src/client/src/index.js
  src/client/src/test/SignIn.test.js
Labels: Front End

#143 Rohan send application to recruiter
  src/client/src/App.js
  src/client/src/components/JobApplication.jsx
  src/client/src/components/JobListing.jsx
  src/client/src/components/JobPosting.jsx
  src/client/src/components/Navbar.jsx
  src/client/src/components/ViewJobsApplied.jsx
  src/client/src/components/receivedApplicationsForRecruiters.jsx
  src/client/src/css/JobPosting.css
  src/client/src/css/jobApplication.css
  src/client/src/css/jobListing.css
  src/client/src/css/receivedApplicationsForRecruiters.css
  src/server/controllers/jobsController.js
  src/server/controllers/usersController.js
  src/server/models/Job.js
  src/server/models/user.js
  src/server/node_modules/.package-lock.json
  src/server/routes/jobsRoutes.js
  src/server/routes/userRoutes.js
  src/server/uploads/64188cd8938a3b5a363890d6-coverLetter.pdf
  src/server/uploads/64188cd8938a3b5a363890d6-resume.pdf
Labels: Front End, Back end

#161 forcing users to upload cv & cl
  src/client/src/components/JobApplication.jsx
Labels: bug fix

#158 Test Case for remove connection feature in the Backend
  src/server/tests/removeConnection.test.js
Labels: Testing
