Repository imran1289-ah/SOEN390-Team05-W23, pull requests merged in 2023-02, with the labels that each got.

#68 Updated mongodb models
  .gitignore
  package-lock.json
  package.json
  src/server/controllers/usersController.js
  src/server/models/Job.js
  src/server/models/Recruiter.js
  src/server/models/UserProfile.js
  src/server/models/user.js
  src/server/routes/uploadResume.js
Labels: Back end

#72 Issue#33/upload resume cl
  src/server/controllers/resumeAndCoverLetterController.js
  src/server/controllers/usersController.js
  src/server/index.js
  src/server/models/user.js
  src/server/routes/uploadResumeCL.js
  src/server/routes/userRoutes.js
Labels: Back end

#85 job posting
  src/client/package-lock.json
  src/client/package.json
  src/client/src/App.js
  src/client/src/components/JobPosting.jsx
  src/client/src/css/JobPosting.css
  src/client/src/test/jobPost.test.js
  src/server/controllers/Jobscontroller.js
  src/server/index.js
  src/server/models/Job.js
  src/server/routes/jobsRoutes.js
  src/server/tests/postJob.test.js
Labels: Front End, Back end

#92 Update README.md
  README.md
Labels: documentation

#94 Added the uploadResume and uploadCoverLetter endpoints to the EditUserProfile frontend
  src/client/src/components/EditUserProfile.jsx
Labels: Front End
