Repository imran1289-ah/SOEN390-Team05-W23, pull requests merged in 2023-04, with the labels that each got.

#167 Rohan tests
  src/client/src/components/JobListing.jsx
  src/client/src/components/Navbar.jsx
  src/client/src/components/ViewJobsApplied.jsx
  src/client/src/components/receivedApplicationsForRecruiters.jsx
  src/client/src/css/receivedApplicationsForRecruiters.css
  src/client/src/css/viewJobsApplied.css
  src/client/src/i18next.js
  src/client/src/test/jobsApplied.test.js
  src/client/src/test/receivedApplications.test.js
Labels: Testing, Front End, bug fix

#165 Attempt to add test case for change website language feature in front end
  src/client/src/test/changeLanguage.test.js
  src/client/src/test/i18nextTest.js
Labels: Testing

#166 Sprint4 fixing tests
  src/server/node_modules/.package-lock.json
  src/server/package-lock.json
  src/server/package.json
  src/server/tests/editJobPosting.test.js
  src/server/tests/editUserProfile.test.js
  src/server/tests/index.test.js
  src/server/tests/jobsWithFilter.test.js
  src/server/tests/postJob.test.js
  src/server/tests/publicUserProfile.test.js
  src/server/tests/sessionController.test.js
Labels: Testing

#172 Adding translation in Jobs Listing page and Jobs Application Page
  src/client/src/components/JobApplication.jsx
  src/client/src/components/JobListing.jsx
  src/client/src/i18next.js
Labels: Front End

#171 Fixed Bugs for job posting
  src/client/src/components/JobPosting.jsx
Labels: bug fix

#170 Notifications features
  src/client/package.json
  src/client/src/components/UserTimeline.jsx
  src/client/src/i18next.js
  src/server/controllers/notificationsController.js
  src/server/routes/userRoutes.js
  src/server/tests/notificationController.test.js
  src/server/tests/roomControllers.test.js
Labels: Front End, Back end

#174 Job Posting features bug fix
  src/client/src/App.js
  src/client/src/components/JobList.jsx
  src/client/src/components/JobPosting.jsx
  src/client/src/components/Navbar.jsx
  src/client/src/css/JobList.css
  src/client/src/i18next.js
  src/server/controllers/jobsController.js
  src/server/controllers/usersController.js
  src/server/models/user.js
  src/server/routes/jobsRoutes.js
Labels: Front End, Back end, bug fix

#175 Job adversitment Feature
  src/client/package-lock.json
  src/client/src/components/JobListing.jsx
  src/client/src/components/JobPosting.jsx
  src/client/src/css/JobPosting.css
  src/client/src/css/jobListing.css
  src/client/src/i18next.js
  src/server/controllers/jobsController.js
  src/server/models/Job.js
  src/server/uploads/642482bcea01977da8088184-coverLetter.pdf
  src/server/uploads/642482bcea01977da8088184-resume.pdf
Labels: Front End, Back end

#176 Direct Message Report Feature
  src/client/package.json
  src/client/src/App.js
  src/client/src/components/Chat.jsx
  src/client/src/components/ChatContainer.jsx
  src/client/src/components/ChatInput.jsx
  src/client/src/components/ChatReportModal.jsx
  src/client/src/components/DMReport.jsx
  src/client/src/components/JobApplication.jsx
  src/client/src/components/Navbar.jsx
  src/client/src/css/ChatContainer.module.css
  src/client/src/css/dmReports.css
  src/client/src/i18next.js
  src/client/src/test/__snapshots__/chat.test.js.snap
  src/client/src/test/chat.test.js
  src/client/src/test/chatmodal.test.js
  src/client/src/test/jobApplication.test.js
  src/server/controllers/reportsController.js
  src/server/index.js
  src/server/models/Reports.js
  src/server/routes/reportsRoutes.js
  src/server/tests/reportsController.test.js
Labels: User story

#183 Adding a responsive navbar
  src/client/src/components/DrawerComponent.jsx
  src/client/src/components/Navbar.jsx
  src/client/src/css/navbar.css
  src/client/src/i18next.js
Labels: Front End

#186 Responsive chat page
  src/client/public/index.html
  src/client/src/components/Contacts.jsx
  src/client/src/css/Chat.module.css
  src/client/src/css/Contacts.module.css
Labels: Front End

#189 Changes to notifications and job preferences
  src/client/src/components/JobListing.jsx
  src/client/src/components/UserTimeline.jsx
  src/client/src/css/jobListing.css
  src/client/src/i18next.js
Labels: enhancement

#187 Admin managing account
  src/client/src/App.js
  src/client/src/components/AdminEditAccount.jsx
  src/client/src/components/DMReport.jsx
  src/client/src/components/DrawerComponent.jsx
  src/client/src/components/ManageAccounts.jsx
  src/client/src/components/Navbar.jsx
  src/client/src/components/SignIn.jsx
  src/client/src/components/UserTimeline.jsx
  src/client/src/css/AdminEditAccount.css
  src/client/src/css/ManageAccounts.css
  src/client/src/css/navbar.css
  src/client/src/i18next.js
  src/server/controllers/adminController.js
  src/server/controllers/usersController.js
  src/server/index.js
  src/server/models/user.js
  src/server/routes/adminRoutes.js
  src/server/tests/admin.test.js
Labels: Front End, Back end

#198 Responsivness of Sign in, sign up, user timeline, edit profile
  src/client/src/App.js
  src/client/src/components/LoginFooter.jsx
  src/client/src/components/SignIn.jsx
  src/client/src/components/SignUp.jsx
  src/client/src/components/UserTimeline.jsx
  src/client/src/css/EditUserProfile.css
  src/client/src/css/loginfooter.module.css
  src/client/src/css/searchuserlist.css
  src/client/src/css/signin.css
  src/client/src/css/signin.module.css
  src/client/src/css/signup.module.css
  src/client/src/css/userTimeline.module.css
Labels: Front End

#193 Sprint5 bugfixes
  src/client/src/components/ChatContainer.jsx
  src/client/src/components/EditUserProfile.jsx
  src/server/controllers/messageController.js
Labels: bug fix

#197 Dm report with attachment
  src/client/src/components/DMReport.jsx
  src/client/src/css/dmReports.css
  src/server/models/Reports.js
Labels: bug fix

#206 Fixing bugs and Responsiveness of Profile page + navbar
  src/client/public/favicon.ico
  src/client/src/App.js
  src/client/src/components/Navbar.jsx
  src/client/src/components/PublicUserProfile.jsx
  src/client/src/components/SearchUser.jsx
  src/client/src/components/UserProfile.jsx
  src/client/src/components/UserTimeline.jsx
  src/client/src/css/loginfooter.css
  src/client/src/css/navbar.css
  src/client/src/css/publicuserprofile.css
  src/client/src/i18next.js
  src/server/controllers/usersController.js
Labels: enhancement, Front End, bug fix

#200 Display changes when the user edits their profile
  src/client/src/App.js
  src/client/src/components/EditUserProfile.jsx
  src/client/src/components/JobList.jsx
  src/client/src/components/waitingConnections.jsx
  src/client/src/css/EditUserProfile.css
  src/client/src/css/JobList.module.css
  src/client/src/css/loginfooter.css
  src/client/src/css/loginfooter.module.css
  src/client/src/css/waitingConnections.module.css
Labels: enhancement

#221 fixing overflow for Chat
  src/client/src/css/Chat.module.css
  src/client/src/css/ChatContainer.module.css
Labels: bug fix

#222 Fixed footer for some pages
  src/client/src/App.js
Labels: bug fix

#192 Updated CSS and Responsiveness - Job Posting and Job Postings Summary
  src/client/src/components/JobList.jsx
  src/client/src/components/JobPosting.jsx
  src/client/src/css/JobList.css
  src/client/src/css/JobList.module.css
  src/client/src/css/JobPosting.css
Labels: enhancement, Front End

#224 Enhancement for job application page
  src/client/src/components/JobApplication.jsx
  src/client/src/css/jobApplication.css
  src/client/src/i18next.js
Labels: enhancement

#226 Haoyi responsiveness
  src/client/package-lock.json
  src/client/src/App.js
  src/client/src/components/EditJobPosting.jsx
  src/client/src/components/JobListing.jsx
  src/client/src/css/JobList.css
  src/client/src/css/editjobposting.css
  src/client/src/css/jobApplication.css
  src/client/src/css/jobListing.css
  src/client/src/css/receivedApplicationsForRecruiters.css
  src/client/src/css/viewJobsApplied.css
  src/client/src/i18next.js
  src/server/controllers/jobsController.js
  src/server/node_modules/.package-lock.json
  src/server/uploads/643706fa690427e8d0a194db-coverLetter.pdf
  src/server/uploads/643706fa690427e8d0a194db-resume.pdf
  src/server/uploads/6437229a956253ae256b4edc-coverLetter.pdf
  src/server/uploads/6437229a956253ae256b4edc-resume.pdf
  src/server/uploads/643ec97416e6148ceaaa46cf-coverLetter.pdf
  src/server/uploads/643ec97416e6148ceaaa46cf-resume.pdf
  src/server/uploads/643f43073a8b1a380800df39-coverLetter.pdf
  src/server/uploads/643f43073a8b1a380800df39-resume.pdf
Labels: Front End, bug fix

#229 System Tests
  src/client/src/App.js
  src/client/src/components/waitingConnections.jsx
  src/client/src/css/editjobposting.css
  src/client/src/css/waitingConnections.css
  src/client/src/i18next.js
  src/server/node_modules/.package-lock.json
  src/server/package-lock.json
  src/server/package.json
  src/server/tests/systemTests/.gitignore
  src/server/tests/systemTests/Admin/Admin.robot
  src/server/tests/systemTests/Admin/admin_resource.robot
  src/server/tests/systemTests/Recruiter/Recruiter.robot
  src/server/tests/systemTests/Recruiter/recruiter_resource.robot
  src/server/tests/systemTests/User/User.robot
  src/server/tests/systemTests/User/user_resource.robot
  src/server/tests/systemTests/files/test.pdf
  src/server/tests/systemTests/resource.robot
Labels: enhancement, Testing, bug fix
